.\" Copyright (c) 2007 Pietro Donatini (pietro.donatini@unibo.it)
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111,
.\" USA.
.\"
.TH libnss_ato 3
.SH NAME
libnss_ato \- All To One nameservice
.SH DESCRIPTION
The libnss_ato module is a set of C library extensions which allows to map every nss request for unknown user to a single predefined user.
.LP
An example
.I /etc/nsswitch.conf
.sp 1n
.PD 0
.TP 16
passwd:
files ato
.TP
group:
files
.TP
shadow:
files ato
.LP
We need shadow in order to prove that the account is not expired.
.LP
.SH AUTHOR
Pietro Donatini
.SH "SEE ALSO"
nsswitch.conf(3)
